services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080/udp"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
