services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args: 
        TARGETARCH: amd64
    environment:
      - BACKEND_HOST=server
      - BACKEND_PORT=8080
      - WEB_PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args: 
        TARGETARCH: amd64
    environment:
      - HOST_NAME=server
      - BACKEND_PORT=8080
    ports:
      - "8080:8080/udp"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
